import {
  Inter,
  Poppins,
  Courier_Prime,
  Alegreya,
  Montserrat,
} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "700", subsets: ["latin"] });
const courier_prime = Courier_Prime({ weight: "700", subsets: ["latin"] });
const alegreya = Alegreya({ weight: "700", subsets: ["latin"] });
const montserrat = Montserrat({ weight: "700", subsets: ["latin"] });
export const metadata = {
  title: "Mood2Game: Discover top-rated games based on your mood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-RKF9XJKVG4"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-RKF9XJKVG4');
        </script>

        <body className={poppins.className}>{children}</body>
      </head>
    </html>
  );
}
