import { Inter, Poppins,Courier_Prime,Alegreya,Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "700", subsets: ["latin"]});
const courier_prime = Courier_Prime({ weight: "700" , subsets: ["latin"]});
const alegreya = Alegreya({ weight: "700" , subsets: ["latin"]});
const montserrat = Montserrat({ weight: "700" , subsets: ["latin"]});
export const metadata = {
  title: "Game2Mouse: Discover top-rated mouse based on your game",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
