import { GoogleTagManager } from "@next/third-parties/google";
import {
  Inter,
  Poppins,
  Courier_Prime,
  Alegreya,
  Montserrat,
} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "700", subsets: ["latin"] });
const courier_prime = Courier_Prime({ weight: "700", subsets: ["latin"] });
const alegreya = Alegreya({ weight: "700", subsets: ["latin"] });
const montserrat = Montserrat({ weight: "700", subsets: ["latin"] });
export const metadata = {
  title: "Mood2Game: Discover top-rated games based on your mood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <body className={poppins.className}>{children}</body>
        <GoogleTagManager gtmId="G-RKF9XJKVG4" />
      </head>
    </html>
  );
}
